language: python
python:
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
  - "pypy3.5"

addons:
  apt:
    packages:
    - doxygen
    - zip
    - curl

script:
  - python -m unittest discover -s tests
  - if [ -n "${TRAVIS_TAG}" ] && [ "${TRAVIS_PYTHON_VERSION}" == "3.6" ]; then
      pip install Sphinx ;
      sphinx-build -b html docs docs/output ;
      cd docs ;
      zip -r docs.zip output/ ;
      curl -w "Status %{http_code}\n" --user ${HMD_USER_PASSWORD} -F "name=doxygen-python-interface" -F "version=${TRAVIS_TAG}" -F language=Python -F archive=@docs.zip $HMD_POST_URL ;
      cd .. ;
    fi

deploy:
  provider: pypi
  user: "TraceSoftwareInternational"
  password: $PYPI_PWD
  on:
    tags: true
    python: '3.6'


